databases:
  - name: consiliumdata
    databaseName: consiliumdata
    user: consiliumdata

services:
  - type: web
    name: consiliumdata
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: consiliumdata
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
